version: '3.8'

services:
  game_db:
    image: postgres:latest
    container_name: game_db
    volumes:
      - ~/.pg/pg_data/django:/var/lib/postgresql/data
    env_file:
      - .env

  frontend:
    image: ps_frontend:latest
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    image: ps_backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - game_db
    command: >
      bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py loaddata ./questions/fixtures/questions.json && gunicorn game.wsgi:application"
    env_file:
      - .env
