# Generated by Django 5.0.3 on 2024-04-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_true',
            field=models.BooleanField(blank=True),
        ),
    ]
