# Generated by Django 5.0.3 on 2024-04-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_is_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_true',
            field=models.BooleanField(),
        ),
    ]
