# Generated by Django 5.0.3 on 2024-04-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_image_alter_question_is_true'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
            ],
        ),
    ]
